### PR TITLE
genslaxiso: enable adding user rootcopy dir

### PR DESCRIPTION
**Pull request by lars18th**
Add support to add a custom user rootcopy directory to the resulting ISO image. It's preferable that the user first copies the current rootcpy to this user target directory and then add his own files to it, before using the genslaxiso script.

### CODE REVIEW

**Comment by lars18th** [comment]
Hi @Tomas-M ,

Based on https://groups.google.com/g/slax-users/c/vKToMbf_GXE

**Comment by lars18th** [comment]
Hi @Tomas-M ,

No comment about this patch? The idea is to leave to the user a simple method to regenerate the ISO including a custom `/rootcopy/` directory. This directory is essential to include/adapt the content to the user's needs. In our environment it's working for some years. And this script doesn't touch anything in the LiveKit library. So please, consider to merge it.

Regards.

**Comment by Tomas-M** [comment]
I don't have environment set up to test this now, but I am a bit confused.
If I understand your code changes correctly, you are setting up two variables, one for excluding the original ISO's rootcopy and another one to set path to /slax/rootcopy=$ROOTCOPY

But this new graft poin ($ROOTCOPY) is not added to the graft points at all? (to $GRAFT variable).... So it will not be added to the final ISO anyway? An I missing anything? :)

By the way I would prefer -r instead of -d as the parameter for adding rootcopy directory, but this is a minor issue and I can live with -d

**Comment by lars18th** [comment]
Hi @Tomas-M ,

Regarding the `-r` or `-d` if you wish then I can change it. Please, let me know it.

> But this new graft poin ($ROOTCOPY) is not added to the graft points at all? (to $GRAFT variable).... So it will not be added to the final ISO anyway? An I missing anything? :)

You're missing this point: 
```
  find . -type f | sed -r "s:^[.]/::" | egrep -v "^boot/isolinux.(bin|boot)$" | egrep -v "^changes/" | egrep -v "$REGEX" | egrep -v "$RCPYEX" | while read LINE; do
```
The VAR used here it's `($RCPYEX)` as the  `($ROOTCOPY)` is used only to generate this one.

Regards.

**Comment by lars18th** [comment]
Hi @Tomas-M ,

No news about this PR? You can merge and change the "-d" parameter to "-r" if you prefer it. Remember that the reason for this patch is to allow the user to generate a custom rootdir directory. More or less, the idea is this: the user decompress the ISO, then update the rootdir content to put inside it his files, and after it finally regenerates the ISO. With this patch this process will be straightforward. Be free the merge the PR or incorporate it manually with your changes. I've used it for several time without troubles.

Regards.

**Comment by Tomas-M** [comment]
I still think there is an error in your script, or I don't understand it at all.
You are setting up two new variables, one is called RCPYEX for excluding the original ISO's rootcopy directory with grep -v $RCPYEX, this is fine. The other variable, called ROOTCOPY, contains the directory defined by the user which should be used as a new rootcopy. But this variable is not used anywhere, so the user's new rootcopy directory will NOT be included in the generated ISO. Or am I missing something?

I would expect to see something like this in the code:

    GRAFT="$GRAFT $ROOTCOPY"

But I don't see it anywhere. I think your changes will not work.
Am I missing something?

**Comment by lars18th** [comment]
Hi @Tomas-M ,

> Am I missing something?

Sorry! I'm missed one line in the PR. When creating the patch of the PR I've missed the key line that adds the rootdir to the ISO image creation.

So please, check it now before any merge.
Regards.

**Comment by Tomas-M** [comment]
merged in https://github.com/Tomas-M/linux-live/commit/05fc3f977d2caa91b12366c4ac9303d0bb0c6ba3
Thank you

**Pull request closed without merging**
